# Generated by Django 5.1.1 on 2024-09-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_subcategory_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.recurrence'),
        ),
    ]
