# Generated by Django 5.1.1 on 2024-09-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_add_recurrence_id_to_expenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrence',
            options={'verbose_name_plural': 'Recurrences'},
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='interval_days',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='month_of_year',
        ),
        migrations.CreateModel(
            name='DailyRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.TimeField()),
                ('recurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='expenses.recurrence')),
            ],
        ),
    ]
