# Generated by Django 5.1.1 on 2024-10-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_converted_recurrences_model_into_a_general_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='recurrence',
        ),
        migrations.DeleteModel(
            name='DailyRecurrence',
        ),
        migrations.DeleteModel(
            name='Recurrence',
        ),
    ]
